-- 0004_create_suggestions.up.sql
--
-- Suggestions are recommendations generated by the rule-based suggestion
-- engine. Each one is the output of a specific rule that detected a
-- behavior pattern worth surfacing to the user (too many missed tasks,
-- effort imbalance, low streak, etc.).
--
-- Design:
--   * `kind` is the rule code (constrained via CHECK to known values).
--   * `severity` lets the UI render with appropriate emphasis.
--   * `status` lifecycle:  active -> dismissed (user) | expired (engine).
--   * `dedup_key` carries the rule-defined identity, typically
--     "<kind>:<iso-year>-W<iso-week>" so the same rule fires at most once
--     per ISO week. The partial unique index enforces it ONLY on active
--     rows, leaving dismissed history intact.
--   * `payload` is JSONB so each rule can attach its own context (the
--     numbers that justified the suggestion) without schema churn.

CREATE TABLE IF NOT EXISTS suggestions (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    kind          TEXT         NOT NULL,
    severity      TEXT         NOT NULL DEFAULT 'warning',
    status        TEXT         NOT NULL DEFAULT 'active',
    title         TEXT         NOT NULL,
    message       TEXT         NOT NULL,
    payload       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    dedup_key     TEXT         NOT NULL,
    generated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at    TIMESTAMPTZ,
    dismissed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT suggestions_kind_valid
        CHECK (kind IN (
            'reduce_workload',
            'smaller_tasks',
            'easier_wins',
            'focus_shift'
        )),
    CONSTRAINT suggestions_severity_valid
        CHECK (severity IN ('info', 'warning', 'critical')),
    CONSTRAINT suggestions_status_valid
        CHECK (status IN ('active', 'dismissed', 'expired'))
);

-- One suggestion per dedup_key total — once a (kind, ISO-week) row exists
-- in ANY status, the engine will not re-create it. This makes dismissals
-- sticky within the week without resurrecting suggestions the user
-- already saw. A new ISO week produces a new dedup_key, so legitimate
-- re-firing next week is unaffected.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_suggestions_dedup
    ON suggestions (dedup_key);

CREATE INDEX IF NOT EXISTS idx_suggestions_status_generated
    ON suggestions (status, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_suggestions_kind
    ON suggestions (kind);

CREATE OR REPLACE FUNCTION suggestions_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_suggestions_set_updated_at ON suggestions;
CREATE TRIGGER trg_suggestions_set_updated_at
    BEFORE UPDATE ON suggestions
    FOR EACH ROW
    EXECUTE FUNCTION suggestions_set_updated_at();
